### ISSUE TITLE
Tracking issue: update collection parameters

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#2088]
Tracking issue for the feature to allow changing parameters of an existing collection. For example, change HNSW or quantization parameters without having to recreate a collection.

### Tasks
- [x] https://github.com/qdrant/qdrant/pull/2083
- [x] https://github.com/qdrant/qdrant/pull/2087
- [x] https://github.com/qdrant/qdrant/pull/2328
- [x] https://github.com/qdrant/qdrant/pull/2090
- [x] https://github.com/qdrant/qdrant/pull/2097
- [x] https://github.com/qdrant/landing_page/pull/229
- [x] Cleanup

**Comment by agourlay** [comment]
@timvisee can be closed?

**Comment by timvisee** [comment]
Implemented indeed! :tada:
