### ISSUE TITLE
Tracking issue: shard snapshot transfer with index

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#2432]
This issue tracks progress on the feature to use snapshots for shard transfers. The shard snapshot will include index and quantization data. This should make the transfer process faster and prevents rebuilding index or quantization data. This is a work in progress, the issue will be updated to reflect latest developments.

### Tasks

- [x] https://github.com/qdrant/qdrant/pull/2406
- [x] https://github.com/qdrant/qdrant/pull/2410
- [x] https://github.com/qdrant/qdrant/pull/2421
- [x] https://github.com/qdrant/qdrant/issues/2532
    - [x] https://github.com/qdrant/qdrant/pull/2571
    - [x] https://github.com/qdrant/qdrant/pull/2562
    - [x] https://github.com/qdrant/qdrant/pull/2563
    - [x] https://github.com/qdrant/qdrant/pull/2554
- [x] https://github.com/qdrant/qdrant/pull/2434
- [x] https://github.com/qdrant/qdrant/pull/2657
- [x] https://github.com/qdrant/qdrant/pull/2813
- [x] https://github.com/qdrant/qdrant/pull/2825
- [x] https://github.com/qdrant/qdrant/pull/2833
- [x] https://github.com/qdrant/qdrant/pull/2873
- [x] https://github.com/qdrant/qdrant/pull/2874
- [x] https://github.com/qdrant/qdrant/pull/2858
- [x] https://github.com/qdrant/qdrant/pull/2881
- [x] https://github.com/qdrant/qdrant/pull/2843
- [x] https://github.com/qdrant/qdrant/pull/2846
- [x] https://github.com/qdrant/qdrant/pull/2467
- [x] https://github.com/qdrant/qdrant/pull/2884
- [x] https://github.com/qdrant/qdrant/pull/2844
- [x] https://github.com/qdrant/qdrant/pull/2870
- [x] https://github.com/qdrant/qdrant/pull/2898
- [x] https://github.com/qdrant/qdrant/pull/2899
- [x] https://github.com/qdrant/qdrant/pull/2903
- [x] https://github.com/qdrant/qdrant/pull/2907
- [x] https://github.com/qdrant/qdrant/pull/2895
- [x] https://github.com/qdrant/qdrant/pull/2951
- [x] https://github.com/qdrant/qdrant/pull/2918
- [x] https://github.com/qdrant/qdrant/pull/2919
- [x] https://github.com/qdrant/qdrant/pull/2924
- [x] https://github.com/qdrant/qdrant/pull/2926
- [x] https://github.com/qdrant/qdrant/pull/2902
- [x] https://github.com/qdrant/qdrant/pull/2989
- [x] https://github.com/qdrant/qdrant/pull/2991
- [x] https://github.com/qdrant/qdrant/pull/3009
- [x] https://github.com/qdrant/landing_page/pull/430

### Backlog

A rough outline of new tasks on this feature:

- [x] Add `PartialSnapshot` state to shard to use during snapshot transfer
- [x] Implement shard transfer using shard snapshot
    - [x] Init collection on remote, switch to `PartialSnapshot` state
    - [x] Take snapshot on sender
    - [x] Sender must instruct receiver to download/recover snapshot
    - [x] Sender must transfer proxy queue to receiver
    - [x] Switch to `Partial` state from sender through consensus
    - [x] Stay in this state for 10 seconds (consensus timeout), then which remote to `Active`
    - [x] Switch to `Active` early if all nodes confirm latest consensus commit
    - [x] Unwrapping queue proxy must not fail
- [x] Add HNSW index to shard snapshot
- [x] Add quantization data to shard snapshot
- [x] Remove gRPC call to request remote REST port, not required anymore
- [x] Add gRPC shard snapshot endpoints
    - [x] Update snapshot transfer logic to use gRPC calls everywhere, removing `reqwest` dependency
    - [x] Remove `GetHttpPort` gRPC API?
- [x] Clean up temporary snapshot after transfer
    - [x] On sender
    - [x] On receiver
- [x] Properly handle `stopped` flag in shard transfer logic
    - [x] Investigate if setting stopped to true for ongoing transfer is possible if transfer gets cancelled externally
    - [x] Stop <ins>create snapshot</ins>, <ins>transfer/recover snapshot</ins> and <ins>transfer queue</ins> operations in the middle.
- [x] Add consensus operation to switch from `PartialSnapshot` to `Partial`, ensuring the transfer is still ongoing
- [x] Improve: before queue proxy transfer, only confirm remote to be in `Partial` state, synchronize consensus just before switching to active
- [x] HTTP client in receiver (downloading snapshot) must support custom configured TLS certs
- [x] Does the gRPC recover call have a timeout? It should not have, recovery can take a long time
- [x] @generall Integration tests
- [x] List shard transfer method in docs

### Future improvements

- [x] Add debug/trace logging during shard snapshot transfer for easier debugging
- [ ] Make cluster manager aware of `PartialSnapshot`
- [ ] Improvement: transfer queue proxy operations in batch, not one by one
      Note: not super critical, it currently uses exactly the same number of operations users used. User batched operations are still batched here.
- [ ] Improvement: proxy segments on snapshot to prevent read lock blocking writes
- [ ] Set shard transfer method:
    - [ ] Switch default method to `snapshot` in Qdrant 1.8
    - [ ] Dynamically select transfer method based on collection state (`stream_records` below indexing threshold)?
- [x] Refactor shard transfer methods in separate modules
- [x] Document shard snapshot transfer state transitions with AsciiFlow
