### ISSUE TITLE
Tracking issue: Shard snapshots cleanup

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#2532]
Main issue:

* [x] https://github.com/qdrant/qdrant/pull/2410

Cleanup:

* [x] OpenAPI definitions for shard snapshot API - #2571
* [x] Handle failure on shard recovery - https://github.com/qdrant/qdrant/pull/2562
* [x] Handle failure on shard loading on startup - https://github.com/qdrant/qdrant/pull/2563
* [x] Auto-cleaning of download dirs - https://github.com/qdrant/qdrant/issues/2533
* [x] Cleaning of temp data during snapshotting - https://github.com/qdrant/qdrant/issues/2497
* [x] Test for snapshot recovery with snapshot, tempdir, and storage on different filesystems - https://github.com/qdrant/qdrant/pull/2554
* [ ] Refactor `move_all` function
