### ISSUE TITLE
Update to upstream tonic v0.10.0

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#2646]
Depends on <https://github.com/qdrant/qdrant/pull/2589>.

We are currently using a custom `tonic` fork. Tonic `v0.10.0` is released which includes the necessary changes. We should switch back to use upstream so we don't have to keep our fork up-to-date.

## Tasks
- [ ] Update `prost` to `v0.12.0` (https://github.com/qdrant/qdrant/pull/2589)
- [ ] Remove `tonic` patch from `Cargo.toml`: https://github.com/qdrant/qdrant/blob/a6164ccda89b00eb361686ed40b90da9fbb1b2c3/Cargo.toml#L150-L152
- [ ] Update `tonic` and related dependencies to `0.10.0`
- [ ] Resolve any conflicts

**Comment by Ayush9026** [comment]
@timvisee sir i will fix this issue.

**Comment by timvisee** [comment]
> @timvisee sir i will fix this issue.

This requires changes outside our control to be merged first, more specifically: https://github.com/tikv/protobuf-build/pull/70

**Comment by xzfc** [comment]
Fixed in #4737.
