### ISSUE TITLE
Tracking issue Geo polygon query

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2703]
This issue keeps track of the outstanding tasks to finish the geo polygon query feature.

- [x] Merge Extend GeoPolygon to support interiors (https://github.com/qdrant/qdrant/pull/2315)
- [x] Cleanup error handling (https://github.com/qdrant/qdrant/issues/2645)
- [x] Update Python local mode (https://github.com/qdrant/qdrant-client/pull/325)
- [x] Prepare reference documentation (https://github.com/qdrant/landing_page/pull/316)
- [x] Review announcement blog post (https://github.com/qdrant/landing_page/pull/333)
