### ISSUE TITLE
Tracking issue: Discovery API

### ISSUE THREAD

**Issue by coszio** [qdrant/qdrant#2790]
To track the development of a new type of search: discovery. This issue will be updated when there are updates

## Tasks
- #2791 
- #2809
- #2820 
- #2834
- #2836 
- #2851 
- #2867
- #2861 
- qdrant/qdrant-client#368
- qdrant/landing_page#408

## Backlog
- [x] Discovery custom scorer (rank + sigmoided score)
- [x] Integrate discovery custom scorer into `QueryVector` enum
- [x] Context of pairs custom scorer (find best zone)
- [x] Allow custom entry point in hnsw
- [x] Discovery internals (2-step search)
    - [x] First step: find best entrypoint
    - [x] Second step: start searching with custom scorer from entrypoint
    - [x] Preprocessing logic for converting ids to vectors
- [x] Interface
    - [x] Use same vector fetching logic from recommendations
    - [x] Create single and batch endpoints 
- [x] Client
  - [x] Local mode
  - [x] rest and grpc clients
- [ ] Docs 
  - [x] qdrant documentation
  - [ ] article
