### ISSUE TITLE
Tracking issue for sparse vector index integration

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#2796]
This issue tracks the necessary tasks to integrate the sparse vector index (https://github.com/qdrant/qdrant/issues/2684) into the engine.

## Refactor vector storage

- [x] Extract quantization logic from `VectorStorage` into `VectorData` (https://github.com/qdrant/qdrant/pull/2797)
- [x] Refactor vector storage to handle dense and sparse vectors as inputs (https://github.com/qdrant/qdrant/pull/2841)

## Implement new sparse storage

- [x] Add `SimpleSparseVectorStorage` implementation which syncs original vectors into RocksDB (https://github.com/qdrant/qdrant/pull/2806)

## Refactor segment

- [x] Turn segment's `VectorType` into an enum for `QueryVector` (https://github.com/qdrant/qdrant/pull/2854)
- [x] Adapt `NamedVectors` to handle `SparseVectors` (https://github.com/qdrant/qdrant/pull/2966)
- [x] Adapt `VectorStruct` (Ivan)

## Integrate new sparse indexes 

- [x] Add upsert operation on `InvertedIndexRam` (https://github.com/qdrant/qdrant/pull/2826)
- [x] New `SparseIndex` for `VectorIndexEnum` based on `InvertedIndex` (https://github.com/qdrant/qdrant/pull/2835) 
- [x] Add sparse vector `RawScorer` for small cardinality (https://github.com/qdrant/qdrant/pull/2915)
- [x] `SparseIndex` implements `VectorIndex` (https://github.com/qdrant/qdrant/pull/2900)
- [x] Benchmark search on `SparseVectorIndex` to find threshold cardinality for plain filter scan (https://github.com/qdrant/qdrant/pull/2947)
- [x] Fall back to plain search (https://github.com/qdrant/qdrant/pull/2963)

**Comment by NirantK** [comment]
>  SparseIndex implements VectorIndex

Should we assume that we can start trying out the API once this is in dev branch?

**Comment by agourlay** [comment]
There will be other bits and pieces to add to have a proper API available.

However we plan to have a dedicated branch with an experimental API for you to try before it makes it to the `dev` branch.

**Comment by NirantK** [comment]
Aah, got it, thanks @agourlay!
