### ISSUE TITLE
Tracking issue for sparse vector GA

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#3124]
Here is the list of outstanding tasks required to ship the [sparse vector feature](https://github.com/qdrant/qdrant/issues/2796)

- [x] more integration tests 
  - https://github.com/qdrant/qdrant/pull/3126
  -  https://github.com/qdrant/qdrant/pull/3127
  - https://github.com/qdrant/qdrant/pull/3138
  - https://github.com/qdrant/qdrant/pull/3159
- [x] finish plain search through inverted index
  - https://github.com/qdrant/qdrant/pull/3113
  - https://github.com/qdrant/qdrant/pull/3161 
- [x] basic recommendation based on plain search
  - https://github.com/qdrant/qdrant/pull/3128
- [x] immutable RAM inverted index is persisted
  - https://github.com/qdrant/qdrant/pull/3131
  - https://github.com/qdrant/qdrant/pull/3168
  - https://github.com/qdrant/qdrant/pull/3154
- [x] fix optimizer for index `on_disk`
  - https://github.com/qdrant/qdrant/pull/3142
  - https://github.com/qdrant/qdrant/pull/3143
  - https://github.com/qdrant/qdrant/pull/3160
- [x] fix mmap index snapshot
  - https://github.com/qdrant/qdrant/pull/3166
- [x] finish Python client and local mode
  - https://github.com/qdrant/qdrant-client/pull/378
  - https://github.com/qdrant/qdrant-client/pull/393
- [x] Rust client 
  - https://github.com/qdrant/rust-client/pull/80 
- [x] BFB that can generate sparse vectors
  - https://github.com/qdrant/bfb/pull/20
- [x] Typescript client
  - https://github.com/qdrant/qdrant-js/pull/56
- [x] run sparse search benchmarks one last time for sanity check
- [x] documentation
  - https://github.com/qdrant/landing_page/pull/445

**Comment by IvanPleshkov** [comment]
persistence PR: https://github.com/qdrant/qdrant/pull/3131
recommendations, discovery, ect PR: https://github.com/qdrant/qdrant/pull/3128
