### ISSUE TITLE
Tracking issue: Issues API

### ISSUE THREAD

**Issue by coszio** [qdrant/qdrant#3471]
This is a tracking issue for following the development of a new API that aims to report some configuration problems to the users:

- [ ] Internal `issues` crate: #3375 
- [ ] Create endpoint (http only): WIP
- [ ] Report missing payload index
- [ ] Report too many collections

**Comment by generall** [comment]
>  Create endpoint (http only): WIP

Might it be part of telemetry?

**Comment by coszio** [comment]
Probably best to make dedicated API to keep it as a beta feature
