### ISSUE TITLE
Tracking issue: shard diff transfer - WAL delta

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#3477]
This issue tracks progress on the feature for just sending the diff as part of shard transfers. This will be based on the WAL delta between two shard replicas. It should significantly reduce the data to transfer in cases where a diff can be resolved.

### Tasks for 1.8

- [x] https://github.com/qdrant/qdrant/pull/3408
- [x] https://github.com/qdrant/qdrant/pull/3426
- [x] https://github.com/qdrant/qdrant/pull/3506
- [x] https://github.com/qdrant/qdrant/pull/3567
- [x] https://github.com/qdrant/qdrant/pull/3573
- [x] #3572
- [x] https://github.com/qdrant/qdrant/pull/3510
- [x] https://github.com/qdrant/qdrant/pull/3550
- [x] https://github.com/qdrant/qdrant/pull/3551
- [x] https://github.com/qdrant/qdrant/pull/3571
- [x] https://github.com/qdrant/qdrant/pull/3588
- [x] https://github.com/qdrant/qdrant/pull/3590
- [x] https://github.com/qdrant/qdrant/pull/3591
- [x] https://github.com/qdrant/qdrant/pull/3593
- [x] https://github.com/qdrant/qdrant/pull/3620
- [x] https://github.com/qdrant/qdrant/pull/3631
- [x] https://github.com/qdrant/qdrant/pull/3610
- [x] https://github.com/qdrant/qdrant/pull/3615
- [x] https://github.com/qdrant/qdrant/pull/3618
- [x] https://github.com/qdrant/qdrant/pull/3642
- [x] https://github.com/qdrant/qdrant/pull/3660
- [x] https://github.com/qdrant/qdrant/pull/3662
- [x] https://github.com/qdrant/qdrant/pull/3659
- [x] https://github.com/qdrant/qdrant/pull/3661
- [x] https://github.com/qdrant/qdrant/pull/3670
- [x] https://github.com/qdrant/qdrant/pull/3671
- [x] https://github.com/qdrant/qdrant/pull/3509
- [x] #3645
- [x] https://github.com/qdrant/qdrant/pull/3679
- [x] #3677
- [x] https://github.com/qdrant/qdrant/pull/3719
- [x] https://github.com/qdrant/qdrant/pull/3725
- [x] #3687
- [x] https://github.com/qdrant/qdrant/pull/3703
- [x] https://github.com/qdrant/qdrant/pull/3728
- [x] https://github.com/qdrant/qdrant/pull/3702
- [x] https://github.com/qdrant/qdrant/pull/3721
- [x] https://github.com/qdrant/qdrant/pull/3723
- [x] https://github.com/qdrant/qdrant/pull/3736
- [x] https://github.com/qdrant/qdrant/pull/3739
- [x] https://github.com/qdrant/qdrant/pull/3757
- [x] https://github.com/qdrant/qdrant/pull/3769
- [x] https://github.com/qdrant/qdrant/pull/3775
- [x] https://github.com/qdrant/qdrant/pull/3835

### Tasks for 1.9
- [x] https://github.com/qdrant/qdrant/pull/3789
- [x] https://github.com/qdrant/qdrant/pull/3792
- [x] https://github.com/qdrant/qdrant/pull/3800
- [x] https://github.com/qdrant/qdrant/pull/3798
- [x] https://github.com/qdrant/qdrant/pull/3847
- [x] https://github.com/qdrant/qdrant/pull/3848
- [x] https://github.com/qdrant/qdrant/pull/3870
- [x] https://github.com/qdrant/qdrant/pull/3882
- [x] https://github.com/qdrant/qdrant/pull/3884
- [x] https://github.com/qdrant/landing_page/pull/736

### Optional tasks
- [x] https://github.com/qdrant/qdrant/pull/3700

### Backlog 1.8

A rough outline of new tasks on this feature:

- [x] Persist truncated and last seen clocks for WAL, and load it form disk
- [x] Once WAL is loaded, scroll through all entries to update last seen clocks
- [x] On incoming operations, clock tag should be accessible
- [x] Incoming operations should update last seen vector clock
- [x] Add endpoint on recovering node: request last seen clock versions to recover from
- [x] Implement extensive unit tests for all clocking logic
  - [x] Clock set tests
  - [x] Clock map tests
  - [x] Test WAL delta resolution
  - [x] Test clock set, clock map and WAL together
  - [x] Integration test: empty transfer 
  - [x] Integration test: recovery node with diff transfer
  - [x] Test: recover C from B from A
  - [x] Test: WAL diff transfer stops in the middle, recovering node also gets new operation, can we redo diff recovery after?
  - [x] Test: WAL delta resolving with gaps
- [x] Reject operations with old clock tags
- [x] Resolve diff from current WAL (on source shard)
- [x] Add “diff” shard transfer method
  - [x] Setup shards/proxies correctly
  - [x] Ask target node for last seen version
  - [x] Resolve diff from current WAL locally
  - [x] Set max truncation point on local shard
  - [x] Transfer WAL diff
  - [x] Set cutoff point on remote shard
  - [x] Finalize (update shard replica states, clean up proxies?)
- [x] Compatibility:
  - [x] Replica set states for diff transfer must be supported by nodes running 1.7
  - [x] Diff transfer method must be usable on a cluster running 1.7 nodes
- [x] Further polishing:
  - [x] Remove +1 from `RecoveryPoint`
  - [x] Merge `{highest,cutoff}_clock_map{,_path}` fields
  - [x] Improve mechanism for falling back if diff transfer fails
    - [x] Add `RestartTransfer` consensus operation?
    - [x] Add version number to peer information?

### Backlog 1.9

- [x] Enable WAL delta transfer by default if all nodes are 1.8+ (<https://github.com/qdrant/qdrant/pull/3702>)
- [x] Migrate to `Recovery` state (<https://github.com/qdrant/qdrant/pull/3659>)
- [x] Handle shard transfer fallback through consensus (<https://github.com/qdrant/qdrant/pull/3703>)
- [x] Resolve all open `// TODO(1.9):` in code
- [x] Migrate `RecoveryToPartial` (<https://github.com/qdrant/qdrant/pull/3757>)
- [x] Document `wal_delta` transfer
- [x] Add/update peer metadata through consensus (<https://github.com/qdrant/qdrant/pull/3702>)
- [x] Further polishing:
  - [x] When setting cutoff point in stream records transfer, only allow failure if method is not implemented ([comment](https://github.com/qdrant/qdrant/pull/3509#discussion_r1499558270))
- [x] #3789

### Other questions

- [x] Heuristic to decide between diff/full transfer, sometimes a full transfer may be more efficient?
      _Answer: not necessary, WAL size is limited, already limiting diff transfers to a sane amount_
