### ISSUE TITLE
[order-by] Tracking issue

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3521]
**Is your feature request related to a problem? Please describe.**

Original issue: https://github.com/qdrant/qdrant/issues/1763

ToDo:

* [x] initial implementation #3493
* [x] Edit `order_by` description to drop ordering by id guarantee #3589 
* [x] Enable selection of efficient query execution strategy #3562
* [x] Enable `order_by` for date-time values #3540
* [x] Extend internal representation of the order-able value (currently - f64), to also be compatible with large i64 values #3533
* [x] ~Get rid of~ https://github.com/qdrant/qdrant/blob/b0aab16b0de67488e2859c8c511c806c8efdf82c/lib/segment/src/data_types/order_by.rs#L7
* [x] #3726
* [ ] Implement feature in local mode qdrant/qdrant-client#491
* [ ] Write documentation qdrant/landing_page#631
