### ISSUE TITLE
[ColBERT] Tracking issue

### ISSUE THREAD

**Issue by IvanPleshkov** [qdrant/qdrant#3684]
This issue tracks the necessary tasks to integrate late Interaction models into the engine.

Epic description: https://www.notion.so/qdrant/Late-Interaction-models-aka-ColBERT-4b6963314fed45909b803ee7ea19d3d8

## New vector storage
- [x] New simple vector storage for multivector data
  - https://github.com/qdrant/qdrant/pull/3718
  - https://github.com/qdrant/qdrant/pull/3885
- [x] Mmap multivector storage
  - https://github.com/qdrant/qdrant/pull/4106
  - https://github.com/qdrant/qdrant/pull/4194
  - https://github.com/qdrant/qdrant/pull/4197
- [x] Quantization support
  - https://github.com/qdrant/qdrant/pull/4202 

## Integration
- [x] Decouple `Vector` type logic. REST API's vector (and vector-related structures) has to be implemented as separate structure and not defined in `segment` crate
  - https://github.com/qdrant/qdrant/pull/3829
  - https://github.com/qdrant/qdrant/pull/3865
  - https://github.com/qdrant/qdrant/pull/4014
- [x] Extend vector type to support multivectors 
  - https://github.com/qdrant/qdrant/pull/3826
  - https://github.com/qdrant/qdrant/pull/3851
  - https://github.com/qdrant/qdrant/pull/4004
- [x] New metric scorer for multivectors
  - https://github.com/qdrant/qdrant/pull/3713
- [x] HNSW support for multivectors
  - https://github.com/qdrant/qdrant/pull/3880
- [x] Multivector support for segment
  - https://github.com/qdrant/qdrant/pull/3963
  - https://github.com/qdrant/qdrant/pull/3973
- [x] Recommendation support

## API
- [x] REST API
  - write & retrieve https://github.com/qdrant/qdrant/pull/4117
  - config improvements https://github.com/qdrant/qdrant/pull/4171
  - basic search support in REST legacy API https://github.com/qdrant/qdrant/pull/4203
  - new universal search
- [x] gRPC API 
  - write & retrieve https://github.com/qdrant/qdrant/pull/4179
  - basic search support in gRPC legacy API https://github.com/qdrant/qdrant/pull/4203
  - new universal search

## Benchmarks
- [x] internals
  - setup https://github.com/qdrant/qdrant/pull/4005
  - improve MaxSim https://github.com/qdrant/qdrant/pull/4023
- [x] end to end

## Misc.
- [x] local mode
- [x] documentation

**Comment by bm777** [comment]
Amazing!

**Comment by prd-tuong-nguyen** [comment]
Has this feature been made available yet?

**Comment by timvisee** [comment]
> Has this feature been made available yet?

Not yet. This will be part of our next release.

**Comment by prd-tuong-nguyen** [comment]
> > Has this feature been made available yet?
> 
> Not yet. This will be part of our next release.

Thank you so much

**Comment by BW-Projects** [comment]
Hey, thanks for the latest release! Do you already have a end-to-end example on how to use colbert and qdrant to index and retrieve documents? Can this already be done?
Thank you!

**Comment by IvanPleshkov** [comment]
> Hey, thanks for the latest release! Do you already have a end-to-end example on how to use colbert and qdrant to index and retrieve documents? Can this already be done? Thank you!

Released, you can find documentation here:
https://qdrant.tech/documentation/concepts/vectors/?q=colbert#multivectors

**Comment by BW-MOM-AI** [comment]
Do you have some code samples on how to use it with the colbert library?

**Comment by BW-Projects** [comment]
Do you have some code samples on how to use it with the colbert library (or ragatouille?) directly?

**Comment by IvanPleshkov** [comment]
> Do you have some code samples on how to use it with the colbert library (or ragatouille?) directly?

we don't have a ready demo using the colbert library directly. Qdrant API is enough to start using colbert vectors

**Comment by prd-tuong-nguyen** [comment]
@IvanPleshkov really cool bro, thank u
