### ISSUE TITLE
[RBAC] Tracking issue

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3777]
### Features we want

- Provide access based on token, which have more granular control than current API / read-only API keys.
- Control granularity
    - Collections
    - API endpoints: read / write / list
    - Subsets of data - by payload filters
    - Apply some arbitrary Claims
- Administration
    - TTL
    - Ability to revoke token
    - Ability to generate token on demand
    - Do not change internal storage

## How it might work

Based on https://jwt.io/ and some basic cryptography

- The original API key (the write API-Key) is known to Qdrant Service and the **Administrator**.

- Administrator confirms that the owner of the token is granted permissions to do stuff, specified in the *token* by ***signing*** the token.
- The token contains **Claims** to follow, when the token is provided.
- Qdrant service checks the signature against current configured API key (all tokens are revoked if API key is changed)
- Qdrant modifies the request and executes it according to the provided **Claims**

## Tasks

* [x] Implement basic extendable structure which will be used to de-serialize JWT token content
  * Basic Claims - TTL, read/write => #3778
* [x] Implement JWT checking middle-ware for REST and gRPC #3813
* Implement claims checking for Points API
  * [x] #3801
  * [x] filters, collection_name => #3849
  * [ ] Implement `payload` claim for payload editing APIs (grep for `CollectionUpdateOperations::PayloadOperation` in rbac code)
* [x] Implement claims checking for Collections API #3863
* [x] Implement claims checking for other APIs (cluster, service, snapshot, update) #3908
* [x] Check if token is not revoked #3874
* [x] Integration of advanced checks into API function (probably in ToC)
  * How to make sure we don't implement unprotected APIs in future? compile time / tests?
* [x] Use new claims schema #3941
* Access TOC/collections by auth object.
  * [x] Preparation: #3925, #3932
  * [x] Make `TableOfContent::get_collection` into `pub(crate)` and use `get_collection_by_pass` instead. #3972
  * [x] `Dispatcher::toc()` should take an auth object. #3972
* [x] Prepare web-ui for JWT token generation qdrant/qdrant-web-ui#175
* [x] Unit tests for `storage::rbac` module. #4006 
* [x] Integration tests (pytest) 
  - #3961 
  - #4008
  - #4017
  - #4038
