### ISSUE TITLE
Tracking issue: resharding

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant#4213]
This issue tracks progress on the resharding feature. It allows to dynamically grow the number of shards in a Qdrant collection.

### Tasks

- [x] #4216
- [x] #4236
- [x] #4255
- [x] #4238
- [x] #4239
- [x] #4217
- [x] #4305
- [x] #4301
- [x] #3499
- [x] #4290
- [x] #4346
- [x] #4349
- [x] #4351
- [x] #4256
- [x] #4355
- [x] #4344
- [x] #4373
- [x] #4379
- [x] #4381
- [x] #4480
- [x] #4417
- [x] #4491
- [x] #4506
- [x] #4501
- [x] #4507
- [x] #4503
- [x] #4493
- [x] #4509
- [x] #4515
- [x] #4516
- [x] #4524
- [x] #4561
- [x] #4565
- [x] #4597
- [x] #4598
- [x] #4319
- [x] #4608
- [x] #4609
- [x] #4642
- [x] #4617
- [x] #4681
- [x] #4666
- [x] #4682
- [x] #4687
- [x] #4704
- [x] #4725
- [x] #4707
- [x] #4699
- [x] #4697
- [x] #5005
- [x] #5019
- [x] #5034
- [x] #4724
- [x] #4736
- [x] #4741
- [x] #5522
- [x] https://github.com/qdrant/qdrant/pull/5736
- [x] #4599
- [x] #5718

### Backlog

A rough outline of new tasks on this feature:

- [x] deduplicate count during resharding
- [x] implement resharding "driver"
  - [x] dedicated task running on receiver node is driving resharding (@timvisee proposal)
- [x] add resharding filter for query API
- [x] on resharding start, clear any existing state
- [x] abort/cancel resharding
  - [x] when participating peer is removed
  - [x] is it possible to remove the only/last replica of a shard? if so, then we also need to cancel resharding when we remove shard replicas
  - [x] when resharding transfer fails
  - [x] when new shard is marked as `Dead`
    - [ ] ensure new shard *can* be marked as `Dead`, even if it's the *only* replica of a shard
- [x] report resharding in cluster info
- [x] report correct number of points transferred in resharding transfer
- [x] fix exact counts while resharding
- [x] ensure compatibility with 1.9.x patch versions that already persisted default resharding state on disk
- [x] extend shard transfer key, include target shard to uniquely identify resharding transfers to
- [x] support scaling down
- [x] revise scale down point migrations:
  - [x] shard transfer to each replica separately using shard transfers (<https://github.com/qdrant/qdrant/pull/4741>)
  - [x] or, keep manual scroll+upsert and add resharding proxy to forward updates to all other replicas
- [x] improve state:
    - [x] extensible state on disk: resharding per shard key, to eventually support concurrent resharding per shard key
    - [x] potentialy merge consensus and resharding driver state into a single structure
- [x] handle resharding when restoring *consensus* snapshot
- [x] testing:
    - [x] extensive testing on chaos testing
    - [x] extensive manual testing with concurrent operations (optimizations, snapshots)
- [x] gate resharding behind behind 1.11 version across consensus
- [x] API:
    - [x] expose resharding structs in OpenAPI spec (<https://github.com/qdrant/qdrant/pull/4599>)
    - [x] implement gRPC API for resharding
- [x] resolve all `TODO(resharding)`'s in the codebase

### Future improvements
- more efficient local point migrations (<https://github.com/qdrant/qdrant/pull/4491>)
- when migrating or deleting points, wait for optimizations to not overload the cluster
- implement concurrent resharding operations, one per shard key
