### ISSUE TITLE
[On disk payload index] Tracking issue

### ISSUE THREAD

**Issue by IvanPleshkov** [qdrant/qdrant#4502]
This issue tracks the necessary tasks to integrate the on-disk-payload-index feature into the engine.

## Keyword Index
- [ ] Mmap multi hash map
- [ ] Mmap keyword field index enum variant

## Numeric Index
- [ ] Persisted histogram
- [ ] Mmap numeric field index enum variant

## Boolean Index
- [ ] Mmap boolean field index enum variant

## Geo Index
- [ ] Mmap geo field index enum variant

## Integration
- [ ] Propagate on-disk flag into payload index
- [ ] REST API
- [ ] gRPC API
