### ISSUE TITLE
Tracking issue: Facets

### ISSUE THREAD

**Issue by coszio** [qdrant/qdrant#4760]
- [x] #4753 
- ~[ ] perf: try roaring bitmap in MapIndex~
- [ ] perf: try count-min for aggregating counts
- [x] perf: faster implementation for full-scan filtered facet
  - #4903  
- [x] LocalShard: collect results from multiple segments 
  - #4785 
- [x] Internal service: add internal grpc interface
  - #4790 
- [x] Timeout support
  - #4792 
- [x] Resolve results from multiple replicas
  - #4798 
- [x] Propagate and merge results from segment into collection
  - #4817 
- [x] Exact mode
  - #4878 
- [x] Expose interface
  - #4848  
  - #4933 
- [x] Enable faceting for integer and uuid payloads
  - #4946 
- [x] Local mode
- [x] Docs

**Comment by deepanshu17** [comment]
Hi @coszio do you have any timeline for this development? By when can we expect a beta release for the Facets Count integration?

**Comment by coszio** [comment]
Hi @deepanshu17, we're expecting to release this for v1.12.0 

In the meantime, once "Expose interface" task is done, you'll be able to test-drive it with `qdrant/qdrant:dev`
